### ISSUE TITLE
Event generates a Capo temporal object on function call.

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#10]
As an example, Event::Serialize() has a following line:
-  var touched = new Capo<bool>(fingerprint, tag.Offset);

Since Fingerprint object and tag.Offset never changes after object creation, 
it can be created at a construction time and can be reused.

**Comment by jaykang920** [comment]
Thanks for your feedback.
As you pointed out, reusing Capo instance may help when a single event is serialized many times (as in server-side application).
However, many events just don't be serialized at all.
So we need *instantiate-on-demand and reuse* approach here.
Will apply your suggestion soon.
