### ISSUE TITLE
Sending Events through AsyncTcpServer seems to be rather unnatural.

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#12]
From the HelloWorld5.Server example, when HelloCase sends a HelloResp, it goes through HelloServer to send to the target Session. 

HelloResp goes through SingleThreadFlow queue, HelloServer Bind callback. 

The SingleThreadFlow queue competes with received events. Therefore, there will be large queueing delay, which is not appropriate for server side response processing. 

Is there any other way to bind Send process directly from HelloCase?

**Comment by jaykang920** [comment]
Yes, in HelloWorld5.Server example, all the events (received/to send) are queued in a single queue of the SingleThreadFlow.
Although it is a very simple example, it demonstrates the key concepts of x2.
In x2, ideally every flows/cases may have chances to handle any application event.
If your x2 application goes more specific (like server-side application), then fine tuning can be done with hub channels and link preprocess delegates, to precisely control your network event flows.

**Comment by keedongpark** [comment]
Thanks for reply. 

Then one example can be : 
 - A SingleThreadFlow "net" subscribes for Hub channel "net" 
 - A SingleThreadFlow "app" subscribes for Hub channel "app" 
 - "net" Flow Preprocess sets _Channel of all received events to "app" 
 - Cases in "app" Flow sets _Channel to "net" when Posting. 
 
The above configuration can separate received and sent event processing. 
This surely is not the best practice, but to clarify my understanding. 

Is it correct?

**Comment by jaykang920** [comment]
Right, that should work.
