### ISSUE TITLE
Q. Case can be dynamically added after Flow startup? 

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#17]
I want to use Case like Actor that can be created and destroyed dynamically. 

- Is there a recommended way to do this? 
- Is this usage not recommended at all? 

Flow.Bind() is a static method and any object can subscribe for it. 
Is this the intended behavior? 
Then Can I make an Actor class and use it dynamically?

**Comment by jaykang920** [comment]
Cases can be added to or removed from a flow at any time.
Flows can be attached to or detached from the hub at any time.
These uses are considered normal.

But just one thing: you should be careful about the initialization and cleanup of dynamic cases/flows.
Once you set up a flow/case structure before `Hub.Startup()`, all the flows and cases are initialized (`Setup()` method is called for cases) during the startup sequence.
But cases/flows added after the startup need to be initialized and cleaned up manually with special care.

**Comment by jaykang920** [comment]
`Flow.Bind()` methods are static for convenience.
Looking into them, they calls `currentFlow.Subscribe()` where the `currentFlow` is a thread-local variable that keeps the flow in which the current thread is running.
This also means that `Flow.Bind()` (`Evnet.Bind()` too) should be called exactly in the flow's execution context.

However, cases inherit from `EventSink` and you can use `Bind()` methods of `EventSink there`.
