### ISSUE TITLE
Q. Possible solution to send performance optimization keeping x2 spirit

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#18]
https://github.com/keedongpark/x2clr/blob/master/model/Instance/doc/distribution.md

Can you review the idea? 

Thanks.

**Comment by jaykang920** [comment]
Thanks so much for your feedback.

As the README of x2 says, the core virtue of x2 is that it forces nothing on developers except an event-driven architectural outline. You may write a new Flow or Link implementation to meet your own need.
But I'd like to suggest you to "measure first, then optimize".

For example the following statement is usually not true.

> Posted events need to wait received event processing till it can be posted to remote.

When one of your link case is expected to be busy, you will usually separate it into a dedicated flow (SingleThread or MultiThread) and there will be no logic (received event) processing there. so your events to send need not wait for logic processing.

Of course there are so many ways to go.
Though default network links are x2 cases, you may even use AsyncTcpServer case and AsyncTcpSession objects as if they were just internal components, saying your case can maintain their references and directly call `Send()` and `Broadcast()` methods.
Why not? But beware. That kind of logic-communication coupling will degrade the flexibility and testability of your distributed application.

**Comment by keedongpark** [comment]
Thanks for the detailed answer. 

Now I seem to understand the way to use x2 to distribute Events. 
So the planned NetFlow would not be necessary. 

But still I have another issue with Preprocess to set Channel names. 

Suppose there are three SingleThreadFlow and each handles different events. 
- Preprocess can set Channel based on events. 
- Is this the recommended way to filter Flows for events? 
  - Then I think there must be a way to handle it easily.

**Comment by keedongpark** [comment]
Oh! Good 

 - Instead of using Preprocess to set Channel, set Channel when Post. 
   - Make a consistent scheme for filtering Flows with Channel name. 
 - Make Flows subscribe for required all Channels. 
   - Flow can subscribe for multiple Channels. 

This can solve all performance issues by filtering Flows with Channels.
