### ISSUE TITLE
Q. List<AppClass> example for Event definition in XML

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#19]
Can you provide examples for following? 
- xpiler / Event seem to support list, map container. 
- It is not clear that xpiler / Event can support application types. 

This is required to send a list of Item data to clients as an example. 

Thanks in advance.

**Comment by jaykang920** [comment]
Thanks for your feedback.

x2clr currently supports only list type. You can use standard .NET List<T> to set or get a list type property.

**Comment by jaykang920** [comment]
For example, when you need a list of custom cell type, you can use as follows:
```
<x2>
    <cell name="Item">
        <property name="Id" type="int32"/>
    </cell>
    ...
    <event name="ItemListResp" id="EventType.ItemListResp">
        <property name="Items" type="list(Item)"/>
    </event>
</x2>
```
```
    // On server-side
    void OnItemListReq(ItemListReq req)
    {
        var resp = new ItemListResp().InResponseOf(req);

        var items = new List<Item>();
        items.Add(item1);
        items.Add(item2);
        resp.Items = items;
        ...
        resp.Post();
    }

    // On client-side
    void OnItemListResp(ItemListResp e)
    {
        List<Item> items = e.Items;
        ...
    }
```

**Comment by jaykang920** [comment]
Please note that we have a difficulty here.
Supporting custom cell type in list and map is not a problem.
But since .NET generic does not generate code like C++ template, we need to hard-code (de)serialization methods for every builtin types and this is a tedious job.
Hope someone help me on this issue, without relying on runtime type reflection.

**Comment by keedongpark** [comment]
Thank you. 

IL2CPP makes reflection void. List is required minimum. 

I think it is enough.
