### ISSUE TITLE
EventSink (to communicate) example on AsyncTcpServer

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#22]
Binding example will be a great help to design Event type/value partition to support distribution. 

Up front design of Events is required considering distribution. 

That can be a great help. 

Thanks in advance.

**Comment by jaykang920** [comment]
Thanks for your feedback.

But I don't know exactly what kind of example you want.
Would you please be more specific?

Up-front design of event hierarchy would help, but you can change your event hierarchy at any time to keep your event routing simple.

**Comment by keedongpark** [comment]
There are many options in designing event hierarchy. 

The following guidelines what I have figured out: 
 * Construction of Cases should be possible with unit tests. 
 * Distributed processing should not change Case event binding 
 * One flow (except Timer) with all required Cases should work for all server functionality 
 
I will go with Cases first and redesign events and event subclassing hierarchy later. 

Detailed question can be asked at that time.

Thank you.
