### ISSUE TITLE
Exception during unit test

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#25]
It is a functional test actually. But it is a great help to learn and design. 

[Code Sample](https://gist.github.com/keedongpark/c2b9a52f28dd439e5fe7a851206ffa9f)

The above example code throws exception when "run all tests". 

Running a single test is fine.

**Comment by jaykang920** [comment]
If you set up and tear down Hub-Flow-Case structure in each test method, you should clean up properly so that previous test flow doesn't affect the next test.

In your current code, calling `Hub.Instance.DetachAll();` after every `Hub.Shutdown();` will do it.

**Comment by keedongpark** [comment]
If you add DetachAll in Hub.Shutdown, it will clear possible errors. 

Thank you.

**Comment by jaykang920** [comment]
More recommended way is: set up and tear down overall Hub-Flow-Case structure with NUnit TestFixtureSetup and TestFixtureTeardown, and running other test methods in the meanwhile.
