### ISSUE TITLE
Q. How to set timeout time when waiting on an Event in coroutine? 

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#27]
Wiki doc shows basic flow, but setup of timeout time is not mentioned. 

Can you explain how? 

Thanks in advance.

**Comment by jaykang920** [comment]
Sorry for poor documentation.

As you can clearly see in [WaitForSingleEvent.cs](https://github.com/jaykang920/x2clr/blob/master/x2/Yields/WaitForSingleEvent.cs), you can specify a `double` timeout in seconds as the last constructor argument.

```
    // Wait for MyEvent for 10 seconds or timeout
    yield return new WaitForSingleEvent(coroutine, new MyEvent(), 10);
```

Similar for `WaitForSingleResponse` and `WaitForMultipleEvents`.

**Comment by jaykang920** [comment]
And if you want to change the default coroutine timeout value (30 seconds by default), please set `Config.Coroutine.DefaultTimeout` as a `double` value in seconds at the application startup.

**Comment by keedongpark** [comment]
Thank you.
