### ISSUE TITLE
communication performance test

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#4]
I tested performance by modifying HeadFirst3.Client and HeadFirst3.Server to send and receive. 
The result is 74,000 PPS on one connection. 

It can help us more if server side performance scales well with increasing number of TCP client connections. 

Typical MMO games have 5 to 10 requests per second from a client and 50 to 200 updates from server to clients near (in area of interest) supposing 10 to 20 players near on average. To support this traffic, the communication must have performance of 200 * 1000 (concurrent users) packets per second on 1000 connections. 

Thanks in advance.

**Comment by jaykang920** [comment]
Yes, performance of the current built-in SocketLinks is not so good. Though x2clr itself is not a dedicated network engine, it is still important to provide a usable default socket link implementation of enough performance. I'm looking around several .NET socket libraries, but not sure when I can test and replace the default SocketLinks at this point. Will appreciate any contribution.

**Comment by jaykang920** [comment]
Re-wrote the default socket links for performance and extensibility in v0.6.0.
