### ISSUE TITLE
이벤트별 인크립션 기능 요청

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#6]
xplier 설정 파일에 encryption 옵션을 추가해서 
중요한 메세지 / 이벤트들은 암호화 해서 통신할 수 있도록 기능 요청합니다.

**Comment by jaykang920** [comment]
x2 구조에서 암호화는 통신 채널 수준의 이슈이기 때문에 단순히 바이너리 데이터 인코딩/디코딩 코드를 산출하는 xpiler와는 관련이 없습니다.
x2clr에서 암호화를 포함한 모든 종단 간 바이너리 데이터 변조는 BufferTransform이과 그 집합인 BufferTransformStack으로 추상화됩니다.
통신에 참여하는 각 종단이 코드에서 동일한 BufferTransformStack을 구성해 사용하면 암호화 통신을 쉽게 구성할 수 있습니다.
x2clr/Transforms에 가장 간단한 변조인 비트 반전과 단순한 블록 암호화를 수행하는 BufferTransform 구현이 샘플로 포함되어 있습니다.
샘플 암호화는 예시일 뿐, 실제 프로덕션 사이트에서 그대로 사용하시면 안됩니다.
