### ISSUE TITLE
x2.Fingerprint::Deserialize() 

### ISSUE THREAD

**Issue by keedongpark** [jaykang920/x2clr#7]
It is rather a question than issue. 

Deserialize does not set its length, nor allocates blocks. 
Is it intended behavior? 

TestSerialization() case also commented out serialize / deserialize test code. 

Confirmation can help me to understand the Fingerprint internals.

**Comment by jaykang920** [comment]
Thanks for your feedback.

Yes, it's an intended behavior.
`Fingerprint.Deserialize()` doesn't set its length nor allocate blocks.
Please note that we never need to build up a fingerprint from scratch.
At the time we call `Fingerprint.Deserialize()`, we are expected to have a fingerprint object with proper length and blocks.
And there is no need to re-build.

**Comment by jaykang920** [comment]
Sorry for the test code commented out.
Will rewrite them soon.

**Comment by jaykang920** [comment]
restored the commented serialization test in FingerprintTests
